### PR TITLE
simplification

### PR DESCRIPTION
**Pull request by Sasha-hi**
Сlean code with clean functions without side effects. 
But incompatible with the previous version.

### CODE REVIEW

**Comment by vzahradnik** [comment]
Hi @Sasha-hi, your changes seem interesting. We'll certainly consider accepting them. Thanks for your contribution.

**Review by vzahradnik — APPROVED** [review]

**Comment by Sasha-hi** [comment]
Thanks. Can you create a new release and deploy a new version to Arduino library?

**Comment by vzahradnik** [comment]
I plan to do that this week. I'll let your know.

**Comment by vzahradnik** [comment]
New release was published. It might take a couple of days for Arduino registry to pick it up. In PlatformIO it's already available:
https://platformio.org/lib/show/11232/Ticker

**Pull request merged**
